/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlobId' : IDL.Text,
});
export const CaptionTrack = IDL.Record({
  'vtt' : IDL.Text,
  'captionLabel' : IDL.Text,
  'language' : IDL.Text,
});
export const UserSettings = IDL.Record({
  'language' : IDL.Text,
  'darkMode' : IDL.Bool,
});
export const Time = IDL.Int;
export const VideoView = IDL.Record({
  'timestamp' : Time,
  'videoId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Video = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'videoBlobId' : ExternalBlob,
  'views' : IDL.Nat,
  'thumbnailBlobId' : ExternalBlob,
  'creatorId' : IDL.Text,
  'captionVtt' : IDL.Text,
  'creatorName' : IDL.Text,
  'uploadTime' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaptionTracks' : IDL.Func([IDL.Text], [IDL.Vec(CaptionTrack)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoCaption' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getWatchHistory' : IDL.Func([], [IDL.Vec(VideoView)], ['query']),
  'incrementViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listReadyVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'removeCaptionTrack' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'setCaptionTrack' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSettings' : IDL.Func([UserSettings], [], []),
  'updateVideoCaption' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateVideoStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateWatchHistory' : IDL.Func([IDL.Text], [], []),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlobId' : IDL.Text,
  });
  const CaptionTrack = IDL.Record({
    'vtt' : IDL.Text,
    'captionLabel' : IDL.Text,
    'language' : IDL.Text,
  });
  const UserSettings = IDL.Record({
    'language' : IDL.Text,
    'darkMode' : IDL.Bool,
  });
  const Time = IDL.Int;
  const VideoView = IDL.Record({ 'timestamp' : Time, 'videoId' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Video = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'videoBlobId' : ExternalBlob,
    'views' : IDL.Nat,
    'thumbnailBlobId' : ExternalBlob,
    'creatorId' : IDL.Text,
    'captionVtt' : IDL.Text,
    'creatorName' : IDL.Text,
    'uploadTime' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaptionTracks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaptionTrack)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoCaption' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getWatchHistory' : IDL.Func([], [IDL.Vec(VideoView)], ['query']),
    'incrementViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listReadyVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'removeCaptionTrack' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'setCaptionTrack' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSettings' : IDL.Func([UserSettings], [], []),
    'updateVideoCaption' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateVideoStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateWatchHistory' : IDL.Func([IDL.Text], [], []),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };