/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaptionTrack {
  'vtt' : string,
  'captionLabel' : string,
  'language' : string,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'avatarBlobId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings { 'language' : string, 'darkMode' : boolean }
export interface Video {
  'id' : string,
  'status' : string,
  'title' : string,
  'videoBlobId' : ExternalBlob,
  'views' : bigint,
  'thumbnailBlobId' : ExternalBlob,
  'creatorId' : string,
  'captionVtt' : string,
  'creatorName' : string,
  'uploadTime' : Time,
}
export interface VideoView { 'timestamp' : Time, 'videoId' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaptionTracks' : ActorMethod<[string], Array<CaptionTrack>>,
  'getSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoCaption' : ActorMethod<[string], string>,
  'getWatchHistory' : ActorMethod<[], Array<VideoView>>,
  'incrementViews' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listReadyVideos' : ActorMethod<[], Array<Video>>,
  'removeCaptionTrack' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'setCaptionTrack' : ActorMethod<[string, string, string, string], undefined>,
  'updateSettings' : ActorMethod<[UserSettings], undefined>,
  'updateVideoCaption' : ActorMethod<[string, string], undefined>,
  'updateVideoStatus' : ActorMethod<[string, string], undefined>,
  'updateWatchHistory' : ActorMethod<[string], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];